### ISSUE TITLE
hexo主题模版改造记录 | weearc的个人博客

### ISSUE THREAD

**Issue by weearc** [weearc/weearc.github.io#30]
https://blog.weearc.top/posts/31380.html 

 相离相惜莫相忘，且行且歌且珍惜

**Comment by weearc** [comment]
友链页面又让我改出问题了…明天和这篇文章一起弄完吧

**Comment by aihuanxiangdexiaohuzi** [comment]
哈哈哈哈，最近我又心血来潮，想搞我的blog了
